version: "3"
services:
  db:
    container_name: basira-db
    env_file: .env.docker.dev
    environment:
      POSTGRES_USER: basira
      POSTGRES_PASSWORD: basira
      POSTGRES_DB: basira_develop
    image: postgres:12.2
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    working_dir: /app
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    container_name: basira-api
    depends_on:
      - db
      - typesense
    env_file: .env.docker.dev
    entrypoint: /app/docker-entrypoint.dev.sh
    ports:
      - "3001:3001"
    working_dir: /app
  web:
    build:
      context: .
      dockerfile: ./client/Dockerfile.dev
    command: /bin/sh -c 'cd client && yarn start'
    container_name: basira-web
    depends_on:
      - api
    env_file: .env.docker.dev
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./:/client
    working_dir: /client
  typesense:
    command: '--data-dir /data --api-key=xyz --enable-cors'
    container_name: basira-typesense
    image: typesense/typesense:0.24.1
    ports:
      - "8108:8108"
    restart: on-failure
    volumes:
      - ./tmp/typesense/data:/data
